import { ComponentType } from 'react';
import { InputAttributes } from 'react-number-format';

export type PatternFormatDesignProps = {
  value: number | any;
  format: string;
  allowEmptyFormatting?: boolean;
  mask?: string;
  patternChar?: string;
  customInput?: ComponentType<InputAttributes>;
  defaultValue?: number | any;
  displayType?: 'text' | 'input' | undefined;
  getInputRef?: any;
  isAllowed?: function;
  valueIsNumericString?: boolean;
  prefix?: symbol | any;
  onValueChange?: function;
  thousandsGroupStyle?: 'lakh' | 'thousand' | 'wan';
  thousandSeparator?: string | boolean;
  renderText?: function | any;
  allowLeadingZeros?: boolean;
  allowNegative?: boolean;
  allowedDecimalSeparators?: [] | any;
  decimalScale?: number;
  decimalSeparator?: string;
  fixedDecimalScale?: true;
  suffix?: string;
  className?: string;
  isNotFormatDecimal?: boolean;
  [key: string]: any;
};
